---
title: "Chapter 3 HW"
author: "Ulices Gonzalez"
date: "March 6th, 2025"
output:
  word_document: default
  pdf_document: default
  html_document:
    fig_height: 4
    highlight: pygments
    theme: spacelab
---

```{r setup, include=FALSE}
# DO NOT ALTER CODE IN THIS CHUNK
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
```

------------------------------------------------------------------------

## Conceptual Questions

### 3. We now review k-fold cross-validation.

#### (a) Explain how k-fold cross-validation is implemented.

Set of observations are divided in to k groups of equal size. Each group/fold is treated as a validation set and the method is fit on the remaining folds. The MSE is used then found using the observations in the held out groups/folds. This is repeated k times with a different group being used as a validation each time. At the end averaging the k test errors will result in the k-fold cv estimate.

#### (b) What are the advantages and disadvantages of k-fold cross validation relative to:

##### i. The validation set approach?

-   K-Fold gives data on the variability of the models performance through the use of using k amount of error estimates.
-   There is less bias in the model since it is trained and validation using all of the data its provided in all of its iterations.
-   Due to each iteration using $\frac{k-1}{k}$ of the data set its more efficient in how it handles data.

##### ii. LOOCV?

-   Given that there is less bias present in the k-fold method this also means that it has higher variance than normal even with a small k.
-   The use of k requires the model to be fit k times which can be inefficient especially if the data set being used is large.

------------------------------------------------------------------------

## Applied Questions

### 5. In Chapter 4, we used logistic regression to predict the probability of default using income and balance on the Default data set. We will now estimate the test error of this logistic regression model using the validation set approach. Do not forget to set a random seed before beginning your analysis.

```{R}
library(caTools)
default <- read.csv("DataSets/Default.csv")
default$default <- ifelse(default$default == "Yes", 1, 0)
default$student <- ifelse(default$student == "Yes", 1, 0)
set.seed(0)
```

#### (a) Fit a logistic regression model that uses income and balance to predict default.

```{R}
defaultFit <- glm(default ~ income + balance, data = default, family = binomial)
summary(defaultFit)
```

#### (b) Using the validation set approach, estimate the test error of this model. In order to do this, you must perform the following steps:

##### i. Split the sample set into a training set and a validation set.

```{R}
defaultSplit = sample.split(default$default, SplitRatio = 0.625)
trainingSet <- subset(default, defaultSplit == TRUE)
validSet <- subset(default, defaultSplit == FALSE)
```

##### ii. Fit a multiple logistic regression model using only the training observations.

```{R}
defaultLRModel <- glm(default ~ income + balance, data = trainingSet, family = "binomial")
```

##### iii. Obtain a prediction of default status for each individual in the validation set by computing the posterior probability of default for that individual, and classifying the individual to the default category if the posterior probability is greater than 0.5.

```{R}
defaultProbability=predict(defaultLRModel, newdata = validSet, type="response")
defaultPrediction <- ifelse(defaultProbability > 0.5, 1, 0)
table(defaultPrediction,validSet$default)
```

##### iv. Compute the validation set error, which is the fraction of the observations in the validation set that are misclassifed.

```{R}
mean(defaultPrediction!=validSet$default) * 100
```

#### (c) Repeat the process in (b) three times, using three different splits of the observations into a training set and a validation set. Comment on the results obtained.

```{R}
defaultSplit = sample.split(default$default, SplitRatio = 0.25)
trainingSet <- subset(default, defaultSplit == TRUE)
validSet <- subset(default, defaultSplit == FALSE)
defaultLRModel <- glm(default ~ income + balance, data = trainingSet, family = "binomial")
defaultProbability=predict(defaultLRModel, newdata = validSet, type="response")
defaultPrediction <- ifelse(defaultProbability > 0.5, 1, 0)
table(defaultPrediction,validSet$default)
mean(defaultPrediction!=validSet$default) * 100

defaultSplit = sample.split(default$default, SplitRatio = 0.5)
trainingSet <- subset(default, defaultSplit == TRUE)
validSet <- subset(default, defaultSplit == FALSE)
defaultLRModel <- glm(default ~ income + balance, data = trainingSet, family = "binomial")
defaultProbability=predict(defaultLRModel, newdata = validSet, type="response")
defaultPrediction <- ifelse(defaultProbability > 0.5, 1, 0)
table(defaultPrediction,validSet$default)
mean(defaultPrediction!=validSet$default) * 100

defaultSplit = sample.split(default$default, SplitRatio = 0.75)
trainingSet <- subset(default, defaultSplit == TRUE)
validSet <- subset(default, defaultSplit == FALSE)
defaultLRModel <- glm(default ~ income + balance, data = trainingSet, family = "binomial")
defaultProbability=predict(defaultLRModel, newdata = validSet, type="response")
defaultPrediction <- ifelse(defaultProbability > 0.5, 1, 0)
table(defaultPrediction,validSet$default)
mean(defaultPrediction!=validSet$default) * 100
```

The misclassification rates among the different splits were overall small and never went past 3% showing that the model is effective at predicting defaults but as the split of data is changed from a small training set and large validation set to a large training set to a small validation set the rate increases overtime.

#### (d) Now consider a logistic regression model that predicts the probability of default using income, balance, and a dummy variable for student. Estimate the test error for this model using the validation set approach. Comment on whether or not including a dummy variable for student leads to a reduction in the test error rate.

```{R}
defaultSplit = sample.split(default$default, SplitRatio = 0.625)
trainingSet <- subset(default, defaultSplit == TRUE)
validSet <- subset(default, defaultSplit == FALSE)
defaultLRModel <- glm(default ~ income + balance + student, data = trainingSet, family = "binomial")
defaultProbability=predict(defaultLRModel, newdata = validSet, type="response")
defaultPrediction <- ifelse(defaultProbability > 0.5, 1, 0)
table(defaultPrediction,validSet$default)
mean(defaultPrediction!=validSet$default) * 100
```

Including the student coefficient does not reduce the misclassification rate and if anything increases it as without student the rate is approximately 2.613% and rises to 2.587% with it student included

### 6. We continue to consider the use of a logistic regression model to predict the probability of default using income and balance on the Default data set. In particular, we will now compute estimates for the standard errors of the income and balance logistic regression coefficients in two different ways: (1) using the bootstrap, and (2) using the standard formula for computing the standard errors in the glm() function. Do not forget to set a random seed before beginning your analysis.

#### (a) Using the summary() and glm() functions, determine the estimated standard errors for the coefficients associated with income and balance in a multiple logistic regression model that uses both predictors.

```{R}
library(boot)
set.seed(1)
defaultSDE <- glm(default ~ income + balance, data = default, family = binomial)
summary(defaultSDE)$coefficients[2:3,]
```

#### (b) Write a function, boot.fn(), that takes as input the Default data set as well as an index of the observations, and that outputs the coefficient estimates for income and balance in the multiple logistic regression model.

```{R}
boot.fn <- function(data, index) 
{
  bootData <- data[index, ]
  bootFit <- glm(default ~ income + balance, data = bootData, family = binomial)
  return(summary(bootFit)$coefficients[2:3,1])
}
```

#### (c) Use the boot() function together with your boot.fn() function to estimate the standard errors of the logistic regression coefficients for income and balance.

```{R}
boot(default, boot.fn, R=100)
```

#### (d) Comment on the estimated standard errors obtained using the glm() function and using your bootstrap function.

The standard error for the income is smaller when using bootstrap compared to the glm standard error. The same could also be said when looking at the standard error for balance between the two methods with the bootstrap standard error being smaller than that of the glm but with a larger difference between the two.

### 7. In Sections 5.3.2 and 5.3.3, we saw that the cv.glm() function can be used in order to compute the LOOCV test error estimate. Alternatively, one could compute those quantities using just the glm() and predict.glm() functions, and a for loop. You will now take this approach in order to compute the LOOCV error for a simple logistic regression model on the Weekly data set. Recall that in the context of classification problems, the LOOCV error is given in (5.4).

#### (a) Fit a logistic regression model that predicts Direction using Lag1 and Lag2.

```{R}
weekly <- read.csv("DataSets/Weekly.csv")
weekly$Direction <- as.factor(weekly$Direction)
weeklyFit <- glm(Direction ~ Lag1 + Lag2, data = weekly, family = binomial)
summary(weeklyFit)
```

#### (b) Fit a logistic regression model that predicts Direction using Lag1 and Lag2 using all but the first observation.

```{R}
weeklyFitEx <- glm(Direction ~ Lag1 + Lag2, data = weekly[-1, ], family = binomial)
summary(weeklyFitEx)
```

#### (c) Use the model from (b) to predict the direction of the first observation. You can do this by predicting that the first observation will go up if P(Direction = "Up"\|Lag1, Lag2) \> 0.5. Was this observation correctly classified?

```{R}
weeklyProbability <- predict(weeklyFitEx, data = weekly[1, ], type = "response")
directionPrediction <- ifelse(weeklyProbability > 0.5, "Up", "Down")
actualDirection <- weekly$Direction[1]
classification <- (directionPrediction == actualDirection)
```

#### (d) Write a for loop from i = 1 to i = n, where n is the number of observations in the data set, that performs each of the following steps:

```{R}
n <- nrow(weekly)
error <- numeric(n)

for (i in 1:n)
{
  # i. Fit a logistic regression model using all but the ith observation to predict Direction using Lag1 and Lag2.
  weeklyForFit <- glm(Direction ~ Lag1 + Lag2, data = weekly[-i, ], family = binomial)
  # ii. Compute the posterior probability of the market moving up for the ith observation.
  forFitProb <- predict(weeklyForFit, newdata = weekly[i, ], type = "response")
  # iii. Use the posterior probability for the ith observation in order to predict whether or not the market moves up.
  forFitPredict <- ifelse(forFitProb > 0.5, TRUE, FALSE) 
  # iv. Determine whether or not an error was made in predicting the direction for the ith observation. If an error was made,then indicate this as a 1, and indicate it as a 0.
  forFitDirection <- weekly$Direction[i] == "Up"
  error[i] <- ifelse(forFitPredict != forFitDirection, 1, 0)
}
```

#### (e) Take the average of the n numbers obtained in (d)iv in order to obtain the LOOCV estimate for the test error. Comment on the results.

```{R}
mean(error)
```
