---
title: "MATH 448 Project Progress Report II"
author: "Ulices Gonzalez"
date: "April 22nd, 2025"
output:
  html_document:
    fig_height: 4
    highlight: pygments
    theme: spacelab
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(DT)
library(knitr)
library(heatmaply)
```

------------------------------------------------------------------------

# Trends in Library Use Before, During, and After the COVID-19 Pandemic

------------------------------------------------------------------------

## Introduction

In March of 2020 COVID-19 was declared a Pandemic Worldwide which disrupted infrastructure, business, travel, and the lifestyles of everyone. Given the way the virus is transmitted many libraries had to close their doors. The American Library Association (ALA) surveyed libraries nationwide which included public and academic libraries, in their findings the ALA reported that almost 99% of participating libraries had limited to no access to their branches. Between March of 2020 to April 2021 most libraries were closed to the public and offered alternative services such as Front Door Service and Virtual Library Catalogs. Having been hired at the time of libraries being reopened nationwide, I and other members of the public were not, and still not aware of the scale at which the Pandemic impacted the use of Library Branches. Libraries are not just used for checking out reading and visual materials but offer many resources to the public which range from computing, literacy programs, student meals, and many more necessities which many members of the public rely on. By looking at patron statistics from 2019 to 2024 it allows a better insight into the current state of library use while allowing us to understand the decline, recovery, and plateau libraries have had to face and still do and what factors have influenced this since.

## Description of Data and Variables

The Chicago Public Library is home to 8 branches across 77 different community areas throughout the city of Chicago and has provided statistics over their library operations through Data.gov for the last 12 years. Visitation by Location is a report of Patrons that visited a given library for services provided while excluding community room and program activities. The Holds by Location is a report of holds placed by patrons at a given library, does not include holds placed online. The Computer Sessions by location is a report of 1 hour and 15-minute computer sessions at a given library, does not exclude consecutive sessions from a given patron. Item Circulations by Location is a report of Items checked out and renewed at a given library branch, renewals are treated as new check outs and are not their own statistic. All four Data Sets present statistics by month with a year-to-date total for each library branch associated with the Chicago Public Library.

By using this data, we can examine trends in library usage but also the impact the pandemic had on the usage of library services overall. Specifically, by looking at the data from 2019 to understand the statistics prior to the pandemic we can get a good idea of where library usage peaked. Considering that the pandemic was officially declared in 2020 the best data to look at for the immediate impact would be 2021 as the data for 2022 would be after some safety guidelines were lifted. Lastly, to see the overall impact the pandemic has had a year after it was officially declared over the data from 2024 will be considered and compared along with that of 2019 and 2021.

## Data Processing

Due to the manner in which The Chicago Public Library data sets are provided, many predictors are separated into their own tables which require some additional work in order to combine them with other statistics collected in a give year. For example Item Circulation, Holds, and Computer Sessions are reported in their own sets so in order to look at their influence on Visitation. This took some work and adjustment but was a feasible task due to the size of each given data set being fixed. Some pieces of data were excluded from the final data set particularly online items, holds placed by patrons outside of a branch, and automatic renewals as these padded the statistics in a manner that treated them as their own library branches.

When processing the data from data.gov into r I began by reading each file and making the process of this easier by creating a function that could handle this faster. Once all the files have been read and I took a look at the data I realize that it would be tedious for each predictor to be output as their own data set. From here I began the process of compiling all the data for a given year into a table which led to the creation of the process_year_data function that would compile all the statistics into a single table with each predictor as its own column. This gave a really good output as the data can now be called however the caveat to this is that each library has a row every month of the year meaning that all 80 libraries now had 12 rows leading to each table for a given year having 960 different rows to examine. This was kept as this allows for an examination of extremes and other relevant data but in order to get a better overview the aggregate_year_data function was created to compile the data further by calculating the sum of all the statistics for a given library. With this now being completed it allowed for the data to finally be analyzed with greater ease and cleaner statistics.

## Descriptive Analysis

Above are the summaries of the data for 2019, 2021, and 2024 which display some relevant data regarding the use of public libraries within the city of Chicago. It’s important to state that the minimum values that are 0 correspond to the closure of a branch during a given month, these values were still included as the library branches would still be used during other times of the year. Considering that the data from 2021 is from during the pandemic, it goes without question that the lower number across all predictors corresponds to the impact that the pandemic had. However, it is notable that even a year after the end of the pandemic the average for all four predictors is much closer to that of the pandemic data. Specifically, if we look at the Mean visitation from 2021 it is under half of what the Median was in 2019, in 2024 while still higher by 25000 it shows that while library visitation is slowly coming back that the pandemic is having a long-lasting impact on the use of libraries throughout the city. However, circulation has remained consistent throughout 2021 – 2024 if we look at the means, Holds and Computer Sessions dropped during the pandemic but are showing signs of recovery with holds being slightly above what was reported in 2019 however the same cannot be said for Computer Sessions as they are still slowly increasing but are still below that of 2019.

Over the course of the 5 years being examined there has been a clear change in the scale of visitation throughout the libraries of Chicago. If we excluded the obvious outliers of the Harold Washington and Sulzer Regional Branches, visitation throughout branches was between 100000 to 300000 in 2019. However, if we look at 2021 it’s not surprising that with safety guidelines visitation would go down between 20000 to 100000. Since then, it has steadily grown with it reaching between 50000 to 175000 in visitation but is a significant decrease from what it once was in 2019.

In 2019 both visitation and circulation were consistent with them having a close relationship with one another. Moving into 2021 there is more variance in the relationship as it seems there was an increase in circulation but decrease in visitation, but it is important to note that this is also at a smaller scale compared to 2019. In 2024 there is an increase in both circulation and visitation, however the relationship is even more spread out than it was during the pandemic with a closer relationship being seen with smaller numbers in both ends. Although both have gone up it is still clear that it is at a smaller scale than in 2019 and only slightly larger than that of 2021. (Obvious outliers are not being considered in this analysis)

When looking at the relationship between holds and visitation it has the largest changes between the three being examined as in 2019 there was consistency in the number of holds increasing as there was less visitation which when compared to 2021 is very similar albeit at a smaller scale and more variability. However, the relationship has gone through a major change in 2024 with the increase in visitation leading to a much closer relationship between holds and visitation with it also being more consistent and even at a slightly larger scale than in 2019. (Obvious outliers are not being considered in this analysis)

Lastly Computer Sessions in 2019 had a clear relationship with visitation, with it being extremely consistent with one another with very few changes. In 2021, however, it is expected that this would become more varied throughout the pandemic along with it going down in scale. Of the three years being examined though, 2024 seems to show the largest change in variance as there is more inconsistency in the relationship between sessions and visitation. It also shows some signs of growth but is closer to that of what was reported in 2021.

## Appendix

### I. Data Read

```{R}
data_dir <- "LibraryData/"

load_year_data <- function(year) 
{
  visitors_file <- paste0(data_dir, year, "Visitors.csv")
  circ_file <- paste0(data_dir, year, "Circ.csv")
  holds_file <- paste0(data_dir, year, "Holds.csv")
  computer_file <- paste0(data_dir, year, "Computer.csv")

  
  visitors <- read_csv(visitors_file)
  circ <- read_csv(circ_file)
  holds <- read_csv(holds_file)
  computer <- read_csv(computer_file)

  return(list(visitors = visitors, circ = circ, holds = holds, computer = computer))
}

data_2019 <- load_year_data(2019)
data_2021 <- load_year_data(2021)
data_2024 <- load_year_data(2024)
```

### II. Data Preparation

#### II.I. Data Processing

```{R}
process_year_data <- function(year, data_list)
{
  visitors <- data_list$visitors
  circ <- data_list$circ
  holds <- data_list$holds
  holds <- holds %>% mutate(across(c(-LOCATION), as.numeric))
  computer <- data_list$computer
  
  visitors_long <- visitors %>% pivot_longer(cols = -LOCATION, names_to = "Month", values_to = "Visitation")
  circ_long <- circ %>% pivot_longer(cols = -LOCATION, names_to = "Month", values_to = "Circulation")
  holds_long <- holds %>% pivot_longer(cols = -LOCATION, names_to = "Month", values_to = "Holds")
  computer_long <- computer %>% pivot_longer(cols = -LOCATION, names_to = "Month", values_to = "Sessions")
  
  month_order <- c("JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER")
  
  visitors_long$Month <- factor(visitors_long$Month, levels = month_order)
  circ_long$Month <- factor(circ_long$Month, levels = month_order)
  holds_long$Month <- factor(holds_long$Month, levels = month_order)
  computer_long$Month <- factor(computer_long$Month, levels = month_order)
  
  visitors_long$LOCATION <- str_trim(visitors_long$LOCATION)
  circ_long$LOCATION <- str_trim(circ_long$LOCATION)
  holds_long$LOCATION <- str_trim(holds_long$LOCATION)
  computer_long$LOCATION <- str_trim(computer_long$LOCATION)
  
  merged_year_data <- visitors_long %>% 
  left_join(circ_long, by = c("LOCATION", "Month")) %>%
  left_join(holds_long, by = c("LOCATION", "Month")) %>%
  left_join(computer_long, by = c("LOCATION", "Month"))

  merged_year_data <- merged_year_data %>%
  mutate(Year = year) %>%
  select(LOCATION, Visitation, Circulation, Holds, Sessions, Month, Year)

  return(merged_year_data)
}

processed_2019 <- process_year_data(2019, data_2019)
processed_2021 <- process_year_data(2021, data_2021)
processed_2024 <- process_year_data(2024, data_2024)
```

#### II.II. Data Aggregation

```{R}
aggregate_year_data <- function(year, data_list) 
{
  visitors <- data_list$visitors
  circ <- data_list$circ
  holds <- data_list$holds
  computer <- data_list$computer
  
  visitors_yearly <- visitors %>%
  mutate(across(c(-LOCATION), as.numeric)) %>%
  mutate(LOCATION = str_trim(LOCATION)) %>%
  group_by(LOCATION) %>%
  summarise(Visitation = sum(across(where(is.numeric)), na.rm = TRUE))
  
  circ_yearly <- circ %>%
  mutate(across(c(-LOCATION), as.numeric)) %>%
  mutate(LOCATION = str_trim(LOCATION)) %>%
  group_by(LOCATION) %>%
  summarise(Circulation = sum(across(where(is.numeric)), na.rm = TRUE))
  
  holds_yearly <- holds %>%
  mutate(across(c(-LOCATION), as.numeric)) %>%
  mutate(LOCATION = str_trim(LOCATION)) %>%
  group_by(LOCATION) %>%
  summarise(Holds = sum(across(where(is.numeric)), na.rm = TRUE))
  
  computer_yearly <- computer %>%
  mutate(across(c(-LOCATION), as.numeric)) %>%
  mutate(LOCATION = str_trim(LOCATION)) %>%
  group_by(LOCATION) %>%
  summarise(Sessions = sum(across(where(is.numeric)), na.rm = TRUE))
  
  merged_year_data <- visitors_yearly %>%
  left_join(circ_yearly, by = "LOCATION") %>%
  left_join(holds_yearly, by = "LOCATION") %>%
  left_join(computer_yearly, by = "LOCATION")
  
  merged_year_data <- merged_year_data %>%
  mutate(Year = year) %>%
  select(LOCATION, Visitation, Circulation, Holds, Sessions, Year)
  
  return(merged_year_data)
}

aggregated_2019 <- aggregate_year_data(2019, data_2019)
aggregated_2021 <- aggregate_year_data(2021, data_2021)
aggregated_2024 <- aggregate_year_data(2024, data_2024)
```

### III. Descriptive analysis

#### III.I. Processed/Aggregated Data Table

```{{R}}
combined_data <- bind_rows(aggregated_2019, aggregated_2021, aggregated_2024)
kable(combined_data)
```

#### III.II. Data Summary

```{R}
summary(aggregated_2019 %>% select(-LOCATION, -Year))
summary(aggregated_2021 %>% select(-LOCATION, -Year))
summary(aggregated_2024 %>% select(-LOCATION, -Year))
```

#### III.III. Data Visualization

##### III.III.I. Scatter Plots

```{R}
options(scipen = 999)

ggplot(aggregated_2019, aes(x = Visitation, y = Circulation)) + geom_point() + labs(title = "Visitation vs. Circulation (2019)", x = "Visitation", y = "Circulation")
ggplot(aggregated_2021, aes(x = Visitation, y = Circulation)) + geom_point() + labs(title = "Visitation vs. Circulation (2021)", x = "Visitation", y = "Circulation")
ggplot(aggregated_2024, aes(x = Visitation, y = Circulation)) + geom_point() + labs(title = "Visitation vs. Circulation (2024)", x = "Visitation", y = "Circulation")
```

```{R}
ggplot(aggregated_2019, aes(x = Visitation, y = Holds)) + geom_point() + labs(title = "Visitation vs. Holds (2019)", x = "Visitation", y = "Holds")
ggplot(aggregated_2021, aes(x = Visitation, y = Holds)) + geom_point() + labs(title = "Visitation vs. Holds (2021)", x = "Visitation", y = "Holds")
ggplot(aggregated_2024, aes(x = Visitation, y = Holds)) + geom_point() + labs(title = "Visitation vs. Holds (2024)", x = "Visitation", y = "Holds")
```

```{R}
ggplot(aggregated_2019, aes(x = Visitation, y = Sessions)) + geom_point() + labs(title = "Visitation vs. Computer Sessions (2019)", x = "Visitation", y = "Computer Sessions")
ggplot(aggregated_2021, aes(x = Visitation, y = Sessions)) + geom_point() + labs(title = "Visitation vs. Computer Sessions (2021)", x = "Visitation", y = "Computer Sessions")
ggplot(aggregated_2024, aes(x = Visitation, y = Sessions)) + geom_point() + labs(title = "Visitation vs. Computer Sessions (2024)", x = "Visitation", y = "Computer Sessions")
```

##### III.III.II. Bar Graphs

```{R}
ggplot(aggregated_2019, aes(x = LOCATION, y = Visitation)) + geom_bar(stat = "identity") + labs(title = "Visitation by Library (2019)", x = "Library Location", y = "Visitation") + 
theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

ggplot(aggregated_2021, aes(x = LOCATION, y = Visitation)) + geom_bar(stat = "identity") + labs(title = "Visitation by Library (2021)", x = "Library Location", y = "Visitation") + 
theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

ggplot(aggregated_2024, aes(x = LOCATION, y = Visitation)) + geom_bar(stat = "identity") + labs(title = "Visitation by Library (2024)", x = "Library Location", y = "Visitation") + 
theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

### IV. Regression Methods Applied

#### IV.I. Linear Regression

##### IV.I.I. Description in 1-2 paragraphs

#### IV.II. Polynomial Regression

##### IV.II.I. Description in 1-2 paragraphs

#### IV.III. Ridge Regression

##### IV.III.I. Description in 1-2 paragraphs

### V. Regression Comparisons
